=== Meirunas/Mario-Kart/new/mariokart.dtd
<!ENTITY % stats "(type,name,speed,accel,weight,handling,traction,M-turbo)">
<!ENTITY % terrain "(land,anti-g,water,air)">
<!ENTITY mariokart "(details)">

<!ELEMENT mariokart (details)+ >
<!ELEMENT details %stats; >

<!ELEMENT type (#PCDATA) >
<!ELEMENT name (#PCDATA)>
<!ELEMENT speed %terrain;>
<!ELEMENT accel (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT handling %terrain;>
<!ELEMENT traction (#PCDATA)>
<!ELEMENT M-turbo (#PCDATA)>

<!ELEMENT land (#PCDATA)>
<!ELEMENT anti-g (#PCDATA)>
<!ELEMENT water (#PCDATA)>
<!ELEMENT air (#PCDATA)>

=== Meirunas/Mario-Kart/new/mariokart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mariokart SYSTEM "mariokart.dtd">
<mariokart>
    <details>
        <type>Bodies</type>
        <name>Standard Kart</name>
        <speed>
            <land>0</land>
            <anti-g>0</anti-g>
            <water>0</water>
            <air>0</air>
        </speed>
        <accel>0</accel>
        <weight>0</weight>
        <handling>
            <land>0</land>
            <anti-g>0</anti-g>
            <water>0</water>
            <air>0</air>
        </handling>
        <traction>0</traction>
        <M-turbo>0</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>Pipe Frame</name>
        <speed>
            <land>-0.5</land>
            <anti-g>-0.5</anti-g>
            <water>0</water>
            <air>-0.5</air>
        </speed>
        <accel>0.5</accel>
        <weight>-0.25</weight>
        <handling>
            <land>0.5</land>
            <anti-g>0.25</anti-g>
            <water>0.5</water>
            <air>-0.25</air>
        </handling>
        <traction>0.25</traction>
        <M-turbo>0.5</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>Mach 8</name>
        <speed>
            <land>0</land>
            <anti-g>0.5</anti-g>
            <water>0</water>
            <air>0.25</air>
        </speed>
        <accel>-0.25</accel>
        <weight>0.25</weight>
        <handling>
            <land>-0.25</land>
            <anti-g>0.25</anti-g>
            <water>0</water>
            <air>-0.25</air>
        </handling>
        <traction>0.25</traction>
        <M-turbo>0</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>Steel Driver</name>
        <speed>
            <land>0.25</land>
            <anti-g>-0.25</anti-g>
            <water>0.5</water>
            <air>-0.75</air>
        </speed>
        <accel>-0.75</accel>
        <weight>0.5</weight>
        <handling>
            <land>-0.5</land>
            <anti-g>-0.5</anti-g>
            <water>0.75</water>
            <air>-0.5</air>
        </handling>
        <traction>0</traction>
        <M-turbo>-0.5</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>Cat Cruiser</name>
        <speed>
            <land>-0.25</land>
            <anti-g>0</anti-g>
            <water>-0.25</water>
            <air>0.25</air>
        </speed>
        <accel>0.25</accel>
        <weight>0</weight>
        <handling>
            <land>0.25</land>
            <anti-g>0</anti-g>
            <water>0</water>
            <air>0.25</air>
        </handling>
        <traction>0</traction>
        <M-turbo>0.25</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>Circuit Special</name>
        <speed>
            <land>0.5</land>
            <anti-g>0.25</anti-g>
            <water>-0.5</water>
            <air>-0.25</air>
        </speed>
        <accel>-0.75</accel>
        <weight>0.25</weight>
        <handling>
            <land>-0.5</land>
            <anti-g>-0.25</anti-g>
            <water>-0.25</water>
            <air>-0.75</air>
        </handling>
        <traction>-0.5</traction>
        <M-turbo>-0.75</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>Badwagon</name>
        <speed>
            <land>0.5</land>
            <anti-g>0</anti-g>
            <water>-0.25</water>
            <air>-0.5</air>
        </speed>
        <accel>-1</accel>
        <weight>0.5</weight>
        <handling>
            <land>-0.75</land>
            <anti-g>-0.5</anti-g>
            <water>-0.25</water>
            <air>-0.75</air>
        </handling>
        <traction>0.5</traction>
        <M-turbo>-1</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>Prancer</name>
        <speed>
            <land>0.25</land>
            <anti-g>0</anti-g>
            <water>0</water>
            <air>0</air>
        </speed>
        <accel>-0.5</accel>
        <weight>-0.25</weight>
        <handling>
            <land>0</land>
            <anti-g>-0.25</anti-g>
            <water>0.25</water>
            <air>0</air>
        </handling>
        <traction>-0.25</traction>
        <M-turbo>-0.25</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>Biddybuggy</name>
        <speed>
            <land>-0.75</land>
            <anti-g>-0.25</anti-g>
            <water>-0.5</water>
            <air>-0.5</air>
        </speed>
        <accel>0.75</accel>
        <weight>-0.5</weight>
        <handling>
            <land>0.5</land>
            <anti-g>0.5</anti-g>
            <water>0.5</water>
            <air>0.25</air>
        </handling>
        <traction>0.25</traction>
        <M-turbo>0.75</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>Landship</name>
        <speed>
            <land>-0.5</land>
            <anti-g>-0.75</anti-g>
            <water>0.5</water>
            <air>-0.25</air>
        </speed>
        <accel>0.5</accel>
        <weight>-0.5</weight>
        <handling>
            <land>0.25</land>
            <anti-g>-0.25</anti-g>
            <water>0.75</water>
            <air>0</air>
        </handling>
        <traction>0.75</traction>
        <M-turbo>0.5</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>Sneeker</name>
        <speed>
            <land>0.25</land>
            <anti-g>0</anti-g>
            <water>-0.25</water>
            <air>0</air>
        </speed>
        <accel>-0.5</accel>
        <weight>0</weight>
        <handling>
            <land>0</land>
            <anti-g>0</anti-g>
            <water>0</water>
            <air>-0.25</air>
        </handling>
        <traction>-0.75</traction>
        <M-turbo>-0.25</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>W 25 Silver Arrow</name>
        <speed>
            <land>-0.25</land>
            <anti-g>0.25</anti-g>
            <water>-0.25</water>
            <air>0</air>
        </speed>
        <accel>0.25</accel>
        <weight>-0.25</weight>
        <handling>
            <land>0.25</land>
            <anti-g>0.25</anti-g>
            <water>0.25</water>
            <air>0</air>
        </handling>
        <traction>0.5</traction>
        <M-turbo>0.25</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>Blue Falcon</name>
        <speed>
            <land>0.25</land>
            <anti-g>0.25</anti-g>
            <water>-0.25</water>
            <air>0</air>
        </speed>
        <accel>-0.25</accel>
        <weight>-0.5</weight>
        <handling>
            <land>-0.25</land>
            <anti-g>0.5</anti-g>
            <water>0.25</water>
            <air>-0.5</air>
        </handling>
        <traction>0</traction>
        <M-turbo>-0.25</M-turbo>
    </details>
    <details>
        <type>Bodies</type>
        <name>Tanooki Kart</name>
        <speed>
            <land>-0.25</land>
            <anti-g>0</anti-g>
            <water>0.25</water>
            <air>0</air>
        </speed>
        <accel>-0.5</accel>
        <weight>0.25</weight>
        <handling>
            <land>0.25</land>
            <anti-g>0</anti-g>
            <water>0.5</water>
            <air>0</air>
        </handling>
        <traction>1</traction>
        <M-turbo>-0.25</M-turbo>
    </details>
    <details>
        <type>Characters</type>
        <name>Baby Peach</name>
        <speed>
            <land>2.25</land>
            <anti-g>2</anti-g>
            <water>2.5</water>
            <air>2.75</air>
        </speed>
        <accel>4</accel>
        <weight>2</weight>
        <handling>
            <land>5</land>
            <anti-g>5</anti-g>
            <water>4.5</water>
            <air>5</air>
        </handling>
        <traction>4.25</traction>
        <M-turbo>4</M-turbo>
    </details>
    <details>
        <type>Characters</type>
        <name>Baby Rosalina</name>
        <speed>
            <land>2.25</land>
            <anti-g>2</anti-g>
            <water>2.5</water>
            <air>2.75</air>
        </speed>
        <accel>4.25</accel>
        <weight>2</weight>
        <handling>
            <land>4.75</land>
            <anti-g>4.75</anti-g>
            <water>4.25</water>
            <air>4.75</air>
        </handling>
        <traction>3.75</traction>
        <M-turbo>4</M-turbo>
    </details>
    <details>
        <type>Characters</type>
        <name>Baby mario</name>
        <speed>
            <land>2.5</land>
            <anti-g>2.25</anti-g>
            <water>2.75</water>
            <air>3</air>
        </speed>
        <accel>4.25</accel>
        <weight>2.25</weight>
        <handling>
            <land>4.5</land>
            <anti-g>4.5</anti-g>
            <water>4</water>
            <air>4.5</air>
        </handling>
        <traction>4</traction>
        <M-turbo>3.75</M-turbo>
    </details>
    <details>
        <type>Characters</type>
        <name>Toadette</name>
        <speed>
            <land>2.75</land>
            <anti-g>2.5</anti-g>
            <water>3</water>
            <air>3.25</air>
        </speed>
        <accel>4.25</accel>
        <weight>2.5</weight>
        <handling>
            <land>4.25</land>
            <anti-g>4.25</anti-g>
            <water>3.75</water>
            <air>4.25</air>
        </handling>
        <traction>3.5</traction>
        <M-turbo>3.75</M-turbo>
    </details>
    <details>
        <type>Characters</type>
        <name>Koopa Troopa</name>
        <speed>
            <land>2.75</land>
            <anti-g>2.5</anti-g>
            <water>3</water>
            <air>3.25</air>
        </speed>
        <accel>4</accel>
        <weight>2.5</weight>
        <handling>
            <land>4.5</land>
            <anti-g>4.5</anti-g>
            <water>4</water>
            <air>4.5</air>
        </handling>
